[project]
name = "transcribe-audio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub<1.0",
    "onnxruntime<1.24",
    "torch<2.6",
    "torchaudio<2.6",
    "whisperx>=3.4.3",
]
